name: 🐛 Bug Report
description: File a bug report
title: "[🐛 Bug]: "
labels: [ I-defect, A-needs-triaging ]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: |
        Include details like:
        - What you were trying to do
        - What you expected to happen
        - What actually happened
        - Any relevant context or configuration
        - Stacktrace or error message if applicable
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproducible Code
      placeholder: |
        (This section renders as code, no need for backticks)

        * We can't fix an issue we can't reproduce.
        * If more than one file is needed, create a new GitHub repository and link it here.
        * Reproduction should be SSCCE: Short, Self Contained, Correct (Compilable), Example.
      render: shell
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Debugging Logs
      placeholder: |
        Note: the stack trace should be in the explanation section above
        Instructions for enabling and referencing logs can be found in the links below
      render: logs
  - type: markdown
    id: link
    attributes:
      value: |
        **Read our [logging documentation](https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/)**
        **Link to a [gist](https://gist.github.com/) if logs are too long**
        &nbsp;

        ## Help us Address Your Issue Faster!
  - type: input
    id: selenium-version
    attributes:
      label: What version of Selenium are you currently using?
      description: Important! The latest released version of Selenium is 4.35 and we can't fix old versions.
      placeholder: e.g., 4.17.0
    validations:
      required: true
  - type: checkboxes
    id: prerequisites
    attributes:
      label: The following statements are true
      options:
        - label: This applies to the most recent version of Selenium (we can't fix old versions)
          required: true
        - label: This hasn't already been reported (I searched and didn't find it)
          required: true
        - label: All information necessary to reproduce the issue has been provided above
          required: true
  - type: dropdown
    id: regression
    attributes:
      label: Did this work for you before?
      options:
        - Not sure, this is my first time trying it
        - Yes this is a regression
    validations:
      required: true
  - type: input
    id: last-good
    attributes:
      label: If yes, what version of Selenium did it work with?
      placeholder: "e.g., 4.8.0"
    validations:
      required: false
  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      options:
        - "--"
        - Windows
        - macOS
        - Linux (specify in the description)
    validations:
      required: true
  - type: dropdown
    id: bindings
    attributes:
      label: Selenium Language Binding
      options:
        - "--"
        - Java
        - Python
        - C#/.NET
        - JavaScript/Node.js
        - Ruby
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Which browsers are you experiencing the issue with?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Edge
        - Safari
        - IE
        - Other (please specify in the description)
  - type: dropdown
    id: grid
    attributes:
      label: Are you using Selenium Grid?
      options:
        - "No"
        - "Yes"
    validations:
      required: true
